### PR TITLE
Linear momentum, x and y directions

### PR DESCRIPTION
**Pull request by konrad-topolski**
Added the functions for calculating the loss of linear momentum in x and y directions.

Overall, the following functions have been added: 

get_force_x_lm, get_force_y_lm,
get_linear_momentum_x_lm, get_linear_momentum_y_lm
get_total_force_x, get_total_force_y,
get_total_linear_momentum_x, get_total_linear_momentum_y

### CODE REVIEW

**Comment by Sbozzolo** [comment]
Hi Konrad, thanks for your contribution!

`kuibit` follows strict conventions to keep its quality high, so there are a few things that need to be done before we can merge your PR. I will be happy to help you through the process. If anything is not clear, let me know. If there are steps you don't want to do, I will take care of them.

- [ ] You should branch off the `next` branch (but in this case `master` is perfectly okay, so don't worry about it)
- [ ] Add an entry to the NEWS file.
- [ ] Run `poetry run black -l 79 cactus_waves.py`. This will clean up all the indentation/spaces, et cetera.
- [ ] Squash your commits into a single one.
- [ ] Add a test in `tests/test_cactus_waves.py`. For your particular case, you can see how the tests are implemented for the 'z' component. What you should do is to re-implement the equations (no copy&paste from `cactus_waves.py`) to make sure that you accidentally didn't implement wrong equations. You can run the test with `poetry run unittest tests/test_cactus_waves.py`. It has to pass.
- [ ] Update the documentation. See last section in `cactus_waves.rst`. 
- [ ] Add docstrings to the function that you defined. You can copy and paste from the docstrings of the corresponding functions for the 'z' axis, but don't forget to change the axis!
- [ ] I think that the equations you implemented are not right, for example, it should be `self.dist ** 2` and not `self.dist ** 1`, but I haven't looked into this into too much detail yet. Please, double check the equations.
- [ ] There is no explanation in the comments of what you are doing and what `A, B, C` are. If you look at `get_force_z_lm`, you will see comments on how the formula was derived from the equation cited in the docstring. It would be great to have the same thing. 

I know that this is an intimidating list, but I will make sure to help you along the way.

Thanks again for the contribution.

**Comment by Sbozzolo** [comment]
Hi @konrad-topolski, are you still interested in finishing up this PR? I can take care of some of the items, if you prefer.

**Comment by konrad-topolski** [comment]
Hi, yes, I am still interested, apologies for the late reply.I'll see if I can contribute something more along the lines of kick phenomenon extraction Best regards Konrad 
Temat: Re: [Sbozzolo/kuibit] Linear momentum, x and y directions (#25)Data: 2021-09-17 17:48Nadawca: "Gabriele Bozzola" Adresat: "Sbozzolo/kuibit" ; DW: "Konrad" ; "Mention" ; 
Hi @konrad-topolski, are you still interested in finishing up this PR? I can take care of some of the items, if you prefer.

**Comment by Sbozzolo** [comment]
Ok, thanks. Let me know if you have any question/problem.

**Comment by Sbozzolo** [comment]
Hi @konrad-topolski. I wanted to have this feature, so I implemented all the aforementioned changes (plus a few more) and I am going to merge this PR to the `next` branch. Thanks for starting this contribution, I hope you can contribute more in the future.

**Pull request merged**
